### ISSUE TITLE
spanner: recurring session deletion error

### ISSUE THREAD

**Issue by grayside** [GoogleCloudPlatform/golang-samples#1093]
The error below has occurred in multiple test runs, appears unrelated to other changes. The specific error extracted below is (re)tried a total of 35 times in the linked build log.

From [go1.13 build log](https://source.cloud.google.com/results/invocations/491881a2-0819-40cf-ad2d-a239e2dafe67/targets/cloud-devrel%2Fgo%2Fgolang-samples%2Fpresubmit%2Fgo113/log) in multiple test runs of #1070:

```
=== RUN   TestSample
2019/11/19 18:46:44 Failed to delete session projects/golang-samples-tests/instances/golang-samples-tests/databases/test-golang-samples-tests-7/sessions/AJSwhAQAAZtS04M65t1ZbONyLquqF4NCB76VjuLCamp9h7eh4OTesRqxc2ZsWw. Error: rpc error: code = NotFound desc = Database not found: projects/golang-samples-tests/instances/golang-samples-tests/databases/test-golang-samples-tests-7
[...]
--- PASS: TestSample (79.23s)
```

**Comment by tbpg** [comment]
Changing this to a bug because the sample may not be cleaning up properly.

**Comment by hengfengli** [comment]
I think this is because the database is dropped before the data client tries to delete session. So the error says "Database not found". 

https://github.com/GoogleCloudPlatform/golang-samples/blob/2eb88b14be2dca75536c709aceccadd68400c9b9/spanner/spanner_snippets/snippet_test.go#L45-L46

https://github.com/GoogleCloudPlatform/golang-samples/blob/2eb88b14be2dca75536c709aceccadd68400c9b9/spanner/spanner_snippets/snippet_test.go#L78-L85

For the above code, I believe deleting database will happen first before client can close all of their sessions.
