### ISSUE TITLE
vision: how to return more than 10 visually similar images

### ISSUE THREAD

**Issue by remotejob** [GoogleCloudPlatform/golang-samples#1557]
How increase number return result, instead default 10

	web, err := client.DetectWeb(ctx, image, nil)
	if err != nil {
		log.Fatalf("Failed to detect labels: %v", err)
	}
	if len(web.VisuallySimilarImages) != 0 {
		for _, page := range web.VisuallySimilarImages {
			log.Println(page.Url)
		}
	}

**Comment by tbpg** [comment]
Hi. I looked quickly at the client and didn't see an option for how to do this. I will ask around, but this may be a limitation of the API, so no promises.

You may have better luck asking these types of questions on StackOverflow. Or, if you have an support agreement with Google Cloud, going through the usual channels for support. This repo is for Go samples that are embedded on cloud.google.com.

**Comment by remotejob** [comment]
Hmm. Looks like Python Javascript implementation support "maxResults": 30
[https://stackoverflow.com/questions/48548552/google-cloud-vision-web-detection-api-returns-only-10-responses](url)

[https://gist.github.com/alexcasalboni/5209c853612132ce72b6](url)

**Comment by tbpg** [comment]
Some of the other methods in this client include a max results argument ([example](https://pkg.go.dev/cloud.google.com/go/vision?tab=doc#Client.DetectFaces)). I'm not sure why `DetectWeb` doesn't. It might be intentional, but I don't know. Maybe there is something we can do?

If you look at the underlying implementation, `DetectWeb` calls `annotateOne` with `maxResults` or `0`, meaning the default number of max results.

**Comment by davidcavazos** [comment]
Is that something that would have to change in the autogenerated libraries?

**Comment by tbpg** [comment]
Yes, I think the client config would need to change. I'm not 100% sure, though.

cc @codyoss @noahdietz

**Comment by noahdietz** [comment]
There is no generator config to specify a default value for a request field so there is nothing the generated client library can do. It seems like the backend returns 10 by default (because the hand-written layer uses a `maxResults` of `0` as @tbpg indicated).

I'd either change the hand written layer or contact the backend team to determine the behavior of sending `0` for `maxResults`.

Hope that helps.

**Comment by tbpg** [comment]
Yes, this seems to be a feature request for the hand-written Vision client. @remotejob, would you mind filing an issue at https://github.com/googleapis/google-cloud-go/issues? That's our repo for the Go client libraries; this repo is for Go samples hosted on cloud.google.com.
