### ISSUE TITLE
functions: deploy cloud function via cloudbuild failed not able to find packages

### ISSUE THREAD

**Issue by marvin5064** [GoogleCloudPlatform/golang-samples#1600]
we have certain private repo dependencies for our cloud function, hence we vendor them in with `go mod vendor`, by reference https://cloud.google.com/functions/docs/writing/specifying-dependencies-go
which recommend us to have `.gcloudignore` for ignoring `go.mod` and `go.sum` hence it can properly reference the vendor directory

however, when it comes deploy with cloudbuild, it fails with error, `cannot find package`, like below:
```
Deploying function (may take a while - up to 2 minutes)...
..............................failed.
ERROR: (gcloud.functions.deploy) OperationError: code=3, message=Build failed: ...ency-service/protobuf/const/v1" in any of:
	/workspace/src/mymain/vendor/github.com/somecompany/some-service/protobuf/const/v1 (vendor tree)
	/usr/local/go/src/github.com/somecompany/some-service/protobuf/const/v1 (from $GOROOT)
	/workspace/src/github.com/somecompany/some-service/protobuf/const/v1 (from $GOPATH)
src/mymain/fetch_exchange_rate_handler.go:12:2: cannot find package "github.com/somecompany/some-service/provider" in any of:
	/workspace/src/mymain/vendor/github.com/somecompany/some-service/provider (vendor tree)
	/usr/local/go/src/github.com/somecompany/some-service/provider (from $GOROOT)
	/workspace/src/github.com/somecompany/some-service/provider (from $GOPATH)
```

to investigate what s really happen in the cloudbuild, we've log some things for debug:
```
Already have image (with digest): gcr.io/cloud-builders/gcloud
Dockerfile
Makefile
cloudbuild_branch.yaml
cloudbuild_release_preprod.yaml
cloudbuild_release_prod.yaml
cloudrun
config
decimal
fetch_exchange_rate_handler.go
fetch_exchange_rate_handler_test.go
gen-mocks.sh
gen-proto.sh
go.mod
go.sum
httpresp
kms
logger
message-bus-types
mocks
protobuf
provider
setup-cloud-scheduler.sh
setup.go
static
storage
time
unify_exchange_rate_handler.go
unify_exchange_rate_handler_test.go
vendor
linebreak
/workspace/src/github.com/somecompany/some-service
linebreak
github.com
linebreak
/workspace
linebreak
```

regarding the cloudbuild steps:
```
  - name: "gcr.io/cloud-builders/gcloud"
    dir: "src/github.com/somecompany/some-service"
    entrypoint: sh
    env:
      - "GOPATH=/workspace"
    args:
      - "-c"
      - |
        ls && \
        echo linebreak && \
        pwd && \
        echo linebreak && \
        ls /workspace/src && \
        echo linebreak && \
        echo $$GOPATH && \
        echo linebreak && \
        gcloud functions deploy \
        ${_PROJECT_NAME}${_FETCH_FUNCTION_NAME} \
        --source=. \
        --entry-point=${_FETCH_FUNCTION_NAME} \
        --region=${_FUNCTION_REGION} \
        --trigger-http \
        --runtime=go113 \
        --memory=128MB
```

as you see, the `/workspace/src/github.com/somecompany/some-service/provider` exists, and the GOPATH is `/workspace`, I wonder which part went wrong
appreciate any advice!

**Comment by tbpg** [comment]
When you do `gcloud functions deploy`, it doesn't grab anything from `GOPATH`. So, it seems like the private packages aren't being included in the `vendor` directory (the "vendor tree" lines also indicate this). Can you confirm if they're there?

**Comment by marvin5064** [comment]
actually, most of the dependencies come from the local files (subdirectory from current path):
```
src/mymain/fetch_exchange_rate_handler.go:12:2: cannot find package "github.com/somecompany/some-service/provider" in any of:
	/workspace/src/mymain/vendor/github.com/somecompany/some-service/provider (vendor tree)
	/usr/local/go/src/github.com/somecompany/some-service/provider (from $GOROOT)
	/workspace/src/github.com/somecompany/some-service/provider (from $GOPATH)
```

which the `provider` is under current directory while doing `gcloud functions deploy`

`$GOPATH` is `/workspace`
`pwd` output is `/workspace/src/github.com/somecompany/some-service`

however, it says:
```
/workspace/src/github.com/somecompany/some-service/provider (from $GOPATH)
```

**Comment by tbpg** [comment]
This situation will hopefully get better with Go 1.14, when it's available. Go 1.14 changed the behavior in module-mode to use the vendor directory if it exists. Right now, with <Go 1.14, here is the problem:

* To use private dependencies, you have to use `vendor`, because the Go Cloud Functions builder doesn't have access to your private dependencies.
* To use packages in subdirectories, you have to use modules, because the Go Cloud Functions builder doesn't know the full import path of your package.
  * Put another way, you import the subdirectory with something like `github.com/somecompany/some-service/provider`. When you call `go build`, it wants to find the `provider` package. So, it looks inside `vendor` and `$GOPATH/src`, can't find it, and returns an error. Because the Cloud Functions builder doesn't _know_ to put your function source code at `$GOPATH/src/github.com/somecompany/some-service`, `go build` can't find it.
  * When you use modules, the import path is specified by the `go.mod` file, so `go` knows where to import `provider` from.

For now, the solution is to copy your subdirectory packages into `vendor`. It's not ideal at all, but it works. You can do this manually, with a deploy script (e.g. part of the Cloud Build steps), or by making the subdirectory its own module (by adding a `go.mod`; this is not ideal because it splits up your module making it more difficult to maintain).

**Comment by tbpg** [comment]
Closing this. We're almost there with the new vendor behavior, so this will get better soon.

**Comment by brianmhunt** [comment]
This still appears to be an issue for `gcloud` deploying Google Cloud Functions.

@tbpg — sorry to ping on this, but has there been any update on the vendor behaviour?  If not, is there any way to track it?

Cheers

**Comment by tbpg** [comment]
@codyoss might have a good workaround.

The `vendor` change happened in Go 1.14. Unfortunately, we're still working on newer versions for Go on Cloud Functions.

**Comment by brianmhunt** [comment]
Thanks @tbpg , I hope you're able to get the newer runtime for GCF up soon.  We'll see what workarounds we can come up with in the mean time (and any suggestions are welcome, of course).  Cheers.

**Comment by gomezjdaniel** [comment]
@tbpg so what's the workaround @codyoss has?

**Comment by codyoss** [comment]
I don't have a great solution here either. I have worked around such cases by scripting away vendoring and/or cp'ing sub-directories into the vendor folder. This should work with terraform too, but you might need to create an archive or something that does not include the `go.sum` and `go.mod` and then start your function deploy from that.

**Comment by gomezjdaniel** [comment]
Yes, indeed I opted for renaming `go.sum` and `go.mod`.

Any ETA on newer Go runtime support for Cloud Functions?

**Comment by tbpg** [comment]
No ETA, but soon! We're working on it!
