### ISSUE TITLE
run: cloudrunci.NewService Should Err With Invalid Input

### ISSUE THREAD

**Issue by grant** [GoogleCloudPlatform/golang-samples#1653]
According to Cloud Run's UI, a service name may only start with a letter and contain up to 63 lowercase letters, numbers or hyphens.

This requirement is not stated or asserted here:
https://github.com/GoogleCloudPlatform/golang-samples/blob/master/internal/cloudrunci/cloudrunci.go#L71

We should err when invoking `NewService` with an invalid name.

Related: https://github.com/GoogleCloudPlatform/golang-samples/issues/1647

**Comment by grant** [comment]
Also, not sure why we need a name in the first place. Maybe it would be easier to just generate one?

**Comment by grant** [comment]
Also, the service name used when invoking `NewService` isn't the actual service name which is used, which is weird.

It produces a service name like: `run_events_pubsub-20200813-171338`

**Comment by grayside** [comment]
1. **Hyphens to underscores:** In my review of the code, it does not seem like hyphen to underscore is converted, I wonder if there was a change between test runs causing confusion?

2. **Unexpected Numeric Suffix:** The numeric suffix is required, and various forms of this exist in all safe end-to-end testing implementations. It prevents concurrent tests of the same sample from cross-referencing each other.

3. **Generated the service name:** A fully randomized name would be difficult to troubleshoot after the fact, such as tracking down the service logs. In most cases we could derive the name from the base directory name, however it has not seemed worth exploring the edge cases to build this feature. Happy to discuss designs.

4. **Why is it not already validated:** Rather than reimplement validation cases from gcloud, we passthru to gcloud to make sure we see the product errors. However, gcloud has such a broad error message for invalid service names that a more granular error response seems like it may be helpful.

**Comment by tbpg** [comment]
@grayside or @grant, will one of you be implementing this?

**Comment by grayside** [comment]
I'd prefer to keep the gcloud validation for now, and I believe the need for this has been resolved in the product though I have not had a chance to verify.
