### ISSUE TITLE
Flood of errors in console when running Datastore sample against local Datastore emulator

### ISSUE THREAD

**Issue by MaxRossGoogle** [GoogleCloudPlatform/golang-samples#24]
I followed the instructions for the Cloud Datastore getting started guide with Go:
https://cloud.google.com/datastore/docs/datastore-api-tutorial

Then I followed the instructions to run the local Datastore emulator:
https://cloud.google.com/datastore/docs/tools/datastore-emulator

Then I restarted my app:
`go run tasks.go`

The output looks like this (with the connection reset message just continuing indefinitely):
Cloud Datastore Task List

Usage:

  new <description>  Adds a task with a description <description>
  done <task-id>     Marks a task as done
  list               Lists all tasks by creation time
  delete <task-id>   Deletes a task

> >

 2016/04/04 21:56:30 transport: http2Client.notifyError got notified that the client transport was broken read tcp 127.0.0.1:51418->127.0.0.1:8687: read: connection reset by peer.
2016/04/04 21:56:30 transport: http2Client.notifyError got notified that the client transport was broken read tcp 127.0.0.1:51419->127.0.0.1:8687: read: connection reset by peer.
2016/04/04 21:56:30 transport: http2Client.notifyError got notified that the client transport was broken read tcp 127.0.0.1:51420->127.0.0.1:8687: read: connection reset by peer.

**Comment by MaxRossGoogle** [comment]
Forgot to mention:
This is on OS X 10.11.4

**Comment by broady** [comment]
I can't reproduce this.

Are you using the latest version of the datastore emulator?

Also, there was a recent update to the google.golang.org/cloud/datastore package to use the new datastore/v1beta3 API.

Ensure you are fully up to date:
`go get -u google.golang.org/cloud/datastore`

**Comment by broady** [comment]
It sounds like the emulator isn't really running on that port. Does port 8687 match the output from `gcloud beta emulators datastore start`?

**Comment by MaxRossGoogle** [comment]
Thanks for the response.

I installed everything fresh last night, after the v1beta3 announcement. I believe the emulator is working correctly because I can go through the getting started guide for other languages and those apps connect successfully.

**Comment by broady** [comment]
OK, I can reproduce this on Mac OS. Will file a bug with the emulator team.

**Comment by broady** [comment]
Ah, I can also reproduce on Linux. I must have misconfigured my Linux box yesterday.

This is because the datastore emulator doesn't support gRPC yet.

**Comment by MaxRossGoogle** [comment]
That would certainly explain it. Can't the Go app connect via json/http rather than gRPC? Presumably that's what the Datastore samples for python, java, and node all do.

**Comment by broady** [comment]
It could, but this sample uses the [google.golang.org/cloud/datastore](http://google.golang.org/cloud/datastore) library, which uses gRPC.

It wouldn't be worth changing the underlying transport. It'd be best to get the emulator working with gRPC!

It's strange that the emulator exposes the environment variables that are specifically for gRPC (`DATASTORE_EMULATOR_HOST` rather than `DATASTORE_HOST`, which was for HTTP/1.1)

**Comment by MaxRossGoogle** [comment]
I have no sense of how much work is involved here, but I bet @pcostell knows.

**Comment by broady** [comment]
Ah, yes. I followed up with Patrick. He's working on it.

**Comment by pcostell** [comment]
Hey all --

There is a [gRPC emulator](https://storage.googleapis.com/gcd/tools/gcd-grpc-1.0.0.zip) available!

It has the same command line options as the normal `gcd.sh` tool, but isn't yet built into the `gcloud` tool. For now it only works with `v1beta3` over `gRPC`, which is why we can't just swap it in for the old emulator, which supports both `v1beta2` and `v1beta3`, but only using proto-over-HTTP.
