### ISSUE TITLE
pubsub: NumGoroutines > 500

### ISSUE THREAD

**Issue by ehduardu** [GoogleCloudPlatform/golang-samples#2416]
Is it possible to set NumGoroutines to 500 or more?

I made tests with` NumGoroutines = 500` and had problems during execution, even after receiving and processing all messages, but the execution not finish (the context timeout is ok).

I noticed that when I lowered NumGoroutines to 100, the execution finished normally. Could it be some limitation in NumGoroutines?

**Comment by hongalex** [comment]
Hi, thanks for reporting! I was able to reproduce this as well but just wanted to get some more information. Is there a specific sample you're referring to? What go version/OS version/how much RAM does the machine running the test have?

**Comment by hongalex** [comment]
Actually, I believe the issue is that by default, streams are capped at 100 per grpc connection. By default, we only allow 4 connections per client, which is a healthy default for users. I recommend decreasing the number of `NumGoroutines` for the purposes of your test. If you wish to actually use 500 streams for production purposes, you will need to increase the grpc connection pool size by doing the following:

```go
opts := []option.ClientOption{
	option.WithGRPCConnectionPool(8),
}
client, err := pubsub.NewClient(ctx, projID, opts...)
```

**Comment by ehduardu** [comment]
thanks, @hongalex 
this is very useful!!
