### ISSUE TITLE
Deprecated JWS package alternative

### ISSUE THREAD

**Issue by greysond** [GoogleCloudPlatform/golang-samples#2419]
The [example code](https://github.com/GoogleCloudPlatform/golang-samples/blob/main/endpoints/getting-started/client/main.go) for making an endpoint request with a generated JWT uses `golang.org/x/oauth2/jws`, however that package is [marked as deprecated](https://github.com/golang/oauth2/blob/master/jws/jws.go#L11-L14). Is there a suggested alternative? The deprecation note mentions copying the source tree into your project, but that seems less than ideal.

**Comment by codyoss** [comment]
If you are looking for a substitute I have used https://pkg.go.dev/github.com/dgrijalva/jwt-go/v4 in the past. I assume it has similarish methods, but it has been a while. When the package was deprecated it was more so because it is not as feature rich as the spec for JWS dictates -- it is not general purpose. But the way it is used in this sample is sound. I am also a maintainer of golang.org/x/oauth2 and I can tell you there is no plan of removing the package anytime soon. Hope that helps!

**Comment by greysond** [comment]
That does help, thanks much!
