### ISSUE TITLE
speech: fix API example deadline to 240s, to avoid GRPC deadline too short error

### ISSUE THREAD

**Issue by mattetti** [GoogleCloudPlatform/golang-samples#246]
The sample code wasn't working for me due to a GRPC setting error:

```
2017/04/27 18:23:36 Could not recognize: code:3 message:"Client GRPC deadline too short. Should be at least: 3 * audio-duration + 5 seconds. Current deadline is: 199.99940906430129 second(s). Required at least: 204 second(s)." 
```

I fixed that by extending the deadline in the context:

```golang
        bgctx := context.Background()
	ctx, _ := context.WithDeadline(bgctx, time.Now().Add(240*time.Second))
	conn, err := transport.DialGRPC(ctx,
		option.WithEndpoint("speech.googleapis.com:443"),
		option.WithScopes("https://www.googleapis.com/auth/cloud-platform"),
	)
```

**Comment by broady** [comment]
Which sample? Shouldn't need to make any modification like this.

**Comment by mattetti** [comment]
Here is the sample I had issues with https://github.com/GoogleCloudPlatform/golang-samples/blob/01f58b1df950edfbe1ff28eff9e870fabe6790fc/speech/livecaption/livecaption.go

**Comment by broady** [comment]
Found out the problem.

Speech API supports only 60 seconds of streaming recognition:
https://cloud.google.com/speech/limits#content

https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1894

We need a better error and/or docs. Either the Speech client or underlying Speech API should return a better error.

**Comment by odeke-em** [comment]
Thank you for reporting this @mattetti, I too encountered the same error, sometime late
last year but things were too noisy for me to file a bug here.

With what @broady deduced in https://github.com/GoogleCloudPlatform/golang-samples/issues/246#issuecomment-319887146, @mattetti might you be interested or have time to send a PR to fix this? If not, no biggie, it might picked up.

**Comment by mattetti** [comment]
@odeke-em unfortunately I moved on and I won't be able to, but thanks a lot for offering.

**Comment by danicat** [comment]
@broady I'll take this one, ok? The new README already states briefly about the limits, but I could make it more explicit in this example. Also, I'll work on a better error message.

**Comment by broady** [comment]
Sounds good. Thanks.

Not sure if you can do anything about the error message, my first thought is it should be fixed in the backend.

**Comment by danicat** [comment]
Ok, I've finally managed to reproduce the error... there are actually two possible scenarios:
1) `2017/09/22 06:14:23 Could not recognize: code:11 message:"Exceeded maximum allowed stream duration of 65 seconds." `
2) `2017/09/22 06:19:46 Could not recognize: code:3 message:"Client GRPC deadline too short. Should be at least: 3 * audio-duration + 5 seconds. Current deadline is: 199.99859053990804 second(s). Required at least: 206 second(s)." `

The scenario 1) seems to happen when you submit a speech fragment and it's duration added to the previous fragments is more than 65 seconds. The scenario 2) seems to happen while you are still speaking the last sentence and the `stream.Recv` call time outs.

The documentation says:
```
* Each StreamingRecognize session is considered a single request even though it includes multiple frames of StreamingRecognizeRequest audio within the stream.
```

I'm going to modify the README to include some notes about the limits, but maybe we could also treat those error codes (3 and 11) to give a better error message in the client itself, instead of printing the raw error message.

What do you think?
