### ISSUE TITLE
GSP602 - HTTP Google Cloud Functions in Go - not working

### ISSUE THREAD

**Issue by vivek-kahodariya** [GoogleCloudPlatform/golang-samples#3226]
In the GSP602 Lab, one of the steps is to deploy cloud function with go111 using the following command:
gcloud functions deploy Gopher --runtime go111 --trigger-http
After executing this command, I get an error:
"ERROR: (gcloud.functions.deploy) argument --runtime: go111 is not a supported runtime. Use gcloud functions runtimes list to get a list of available runtimes"

**Comment by chiragkhatri19** [comment]
Getting the same error and I've already tried it 5 times

**Comment by arun-jangir** [comment]
gcloud functions deploy HelloWorld --runtime go111 --trigger-http

 I have also tried but have not gotten desired output as same error encountered because go111 is not a supported runtime
 
![go111](https://github.com/GoogleCloudPlatform/golang-samples/assets/137412681/5936e5ca-a7df-492a-8cc3-9f471891acfc)

**Comment by yashashwini16** [comment]
Yep! , even I'm getting same error! Tried many times but no use ....
Any idea how to rectify?

**Comment by yjhunjhunwala1** [comment]
go111 runtime is not supported for the Lab, we are unable to complete the lab

**Comment by rocpoc** [comment]
@yashashwini16 @yjhunjhunwala1 @arun-jangir @chiragkhatri19 @vivek-kahodariya 

Lab has been updated to use Go 1.20 runtime and should be fixed now.

**Comment by yashashwini16** [comment]
yep! It's working, Thank you .
