### ISSUE TITLE
Trace is not shown

### ISSUE THREAD

**Issue by mblasi** [GoogleCloudPlatform/golang-samples#364]
Hi!

With this sample code I'm not able to see any trace in the trace list view....
Neither with exactly this sample, nor by adding traceClient.SpanFromRequest(r) //which should create a new span...
The only way to see a trace is by adding traceClient.NewSpan("name").

What am I missing?

Regards,
Matías.

**Comment by tbpg** [comment]
Hi @mblasi. Would you mind posting a complete code snippet, what you expect to see, and what you're seeing instead? It would help to diagnose what the issue is.

You may need to add the line:
```go
trace.SetDefaultSampler(trace.AlwaysSample())
```

See https://godoc.org/go.opencensus.io/trace#hdr-Enabling_Tracing_for_a_Program. Let me know if that works for you and I'll update the sample to add a comment (or feel free to send a PR).
