### ISSUE TITLE
error-reporting: fix up sample

### ISSUE THREAD

**Issue by broady** [GoogleCloudPlatform/golang-samples#53]
The whole divide by zero thing is weird. Just use `panic` or remove the panic/defer code completely.

**Comment by odeke-em** [comment]
At @broady you mean this https://github.com/GoogleCloudPlatform/golang-samples/blob/be19f2b968157194852798eedd410de164a617c1/docs/error-reporting/fluent/main.go#L55-L69

IMHO it suffices and doesn't need removing to use panic, because it shows the user how to capture the stacktrace for their bug report. What do you think?

**Comment by broady** [comment]
Yep, that one.

I guess it's fine, but I don't fully understand the usage of error reporting for Go. Do we really want people to only use it for panics?

/cc @rakyll

**Comment by brotherhod** [comment]
There's a package that may simplify the code a little; github.com/pkg/errors
Thus 
// Handler for the incoming requests. 
 func demoHandler(w http.ResponseWriter, r *http.Request) { 
 	err := errors.Error("Runtime Issue with demoHandler")
        if err != nil {
            report(err, r)
        }
}
The report func will now accept an Error rather than a string and using the errors.Errorf("%+v", err) the stack trace can be viewed.  
I'm not sure, though, how helpful stack traces are as Rob Pike has written that errors should be given context before before bubbled up the stack or dealt with.  Using the errors pkg we could now wrap one context within another potentially creating a much nicer and helpful error message rather than a stack trace (remembers screens full of java stack traces....!)  Just my two pennies.

**Comment by tbpg** [comment]
@broady @odeke-em I haven't seen any feedback about this. Do you still have ideas about how to improve it, or should we close this?

@brotherhod Thanks for the link and example. I'd prefer to avoid using any additional external dependencies.

**Comment by tbpg** [comment]
Declaring issue bankruptcy on this. Feel free to reopen if you want to fix it.
