### ISSUE TITLE
Unable to get stackdriver logging working in GAE standard (Golang)

### ISSUE THREAD

**Issue by camstuart** [GoogleCloudPlatform/golang-samples#602]
# Synopsis

Unable to get simple logging in stackdriver working in GAE Standard for Go in a consistent manner local and cloud environments, and in a consistent manner with GAE Flexible for Go.

# Setup

I have stackdriver working in my GCP account. (API enabled) which the docs suggest should be the default behaviour for GAE projects anyway.

And I can confirm that I can see basic request details being logged, in this case: `/test` gives me an entry in the stackdriver viewer with the `200` status code as expected.

<img width="779" alt="screen shot 2018-09-07 at 7 55 27 pm" src="https://user-images.githubusercontent.com/3146022/45212358-0b799e80-b2d8-11e8-9059-5bac82e595b3.png">

# Example Code

I have cut my code down as much as possible to:

```Golang
package main

import (
	"fmt"
	"log"
	"net/http"

	"cloud.google.com/go/logging"
	"google.golang.org/appengine"
)

const (
	appID     = "sd-logger"
	projectID = "thingamewhatsit"
)

func init() {
	http.HandleFunc("/test", handleTest)
}

func main() {
	appengine.Main()
}

func handleTest(w http.ResponseWriter, r *http.Request) {
	// ctx := context.Background() <- "panic serving 127.0.0.1:62808: not an App Engine context"
	ctx := appengine.NewContext(r)
	lc, err := logging.NewClient(ctx, projectID)
	if err != nil {
		log.Fatalf("Failed to create client: %v", err)
	}
	defer lc.Close()
	logger := lc.Logger(appID).StandardLogger(logging.Info)

	msg := "creating a stackdriver log message here!!"
	fmt.Fprintln(w, msg)
	logger.Println(msg) // <- "logging client: rpc error: code = PermissionDenied desc = The caller does not have permission"
}
```

# Problems Encountered:

## 1) Inconsistent `context` in docs

All the docs I can find import `"golang.org/x/net/context"` however, App Engine standard complains that is `not an App Engine context` Instead I use: `ctx := appengine.NewContext(r)`

## 2) logger.Println(msg) not visible in stackdriver console

Expanding the json, and using the search facility still doesn't show the result of the log message

## 3) Permission Denied when running locally 

`dev_appserver.py app.yaml --support_datastore_emulator=True --port=1883` 

I am aware that hitting stackdriver's API from my workstation would require the environment variable `GOOGLE_APPLICATION_CREDENTIALS` to point to a service account file with approriate permissions.

Even with maximum permissions (Owner), I still can't get anything other than "The caller does not have permission" however, I am less concerned about that.

My main objective is to simply have log messages come out in the `dev_appserver.py` output. While developing locally, I would expect the default behaviour to NOT post the logs to the cloud. I think it would be too easy to polute stackdriver entries. 

And when I work locally, I expect my logs to be local and more readily accessable by simply being displayed amongst the existing execution output.

In this scenario, I feel the expected behaviour would be to only output log messages to the console when running under `dev_appserver.py`

Unless an explicit flag is passed, or environment variable set, would the logs to go to stackdriver (and therfore requiring a correct service account configuration) 

## 4) Lack of app engine context in `init()`

I would much prefer to initialise the logger in an `init()` function, however the creation of context is not possible without acceess to a live `*http.Request` variable

Ideally, the `logger` variable would be declared as a global, initialised during `init()` so there is no code duplication if the project has multiple handlers, and also no need to pass the logger around if handlers call functions

**Comment by camstuart** [comment]
Further to this, it would seem stackdriver logging works perfectly by using the appengine log package:

`google.golang.org/appengine/log`

# Working Example

```Golang
package main

import (
	"fmt"
	"net/http"

	"google.golang.org/appengine"
	"google.golang.org/appengine/log"
)

func init() {
	http.HandleFunc("/test", handleTest)
}

func main() {
	appengine.Main()
}

func handleTest(w http.ResponseWriter, r *http.Request) {
	ctx := appengine.NewContext(r)

	var (
		num1 = 10
		num2 = 90
	)
	result := (num1 + num2)

	log.Infof(ctx, "result of: (%d + %d) = %d", num1, num2, result)
	log.Errorf(ctx, "here is some sort of error")
	log.Debugf(ctx, "this message is debug only")

	fmt.Fprintln(w, "hey!")
}
```

# Result

<img width="852" alt="screen shot 2018-09-07 at 9 25 22 pm" src="https://user-images.githubusercontent.com/3146022/45216628-9f516780-b2e4-11e8-9124-bddbfff934b5.png">


This being the case, what is the purpose of `logging.NewClient`? and all the examples using that approach?

**Comment by tbpg** [comment]
Hi. Thank you for trying it out and the thorough bug report!

As you discovered, while running on AppEngine Standard (for now) you have to use `"google.golang.org/appengine/log"` for logging ([docs](https://cloud.google.com/appengine/docs/standard/go/logs/)). The reason is as part of AppEngine Standard's current architecture, it enforces limits on what packages user code can run. You discovered this with `context.Context`, as well. It also means you can't use [`http.DefaultClient`](https://golang.org/pkg/net/http/#pkg-variables) -- you have to use [`urlfetch`](https://cloud.google.com/appengine/docs/standard/go/issue-requests).

This is not ideal. The second generation AppEngine Standard Go runtime will not have these limitations -- you should be able to use whatever packages you want. We're hoping to release it by the end of the year.

I'm going to close this, but feel free to link to the exact documentation you found and if you have any ideas for how it could be improved. Thanks, again, for trying this out and the awesome bug report. It's really appreciated.

**Comment by camstuart** [comment]
Thanks @tbpg;

Here are some docs that demonstrate alternative methods of logging into stackdriver:

- https://cloud.google.com/logging/docs/setup/go
- https://cloud.google.com/appengine/docs/standard/go/logs/

I think the confusion stems from the fact that `google.golang.org/appengine/log` is one option (for GAE projects only)

But other options exist, such as sending via the stackdriver API.

I would be happy to provide samples for logging with detailed explanations in a README via a PR to this section of your samples repo:
https://github.com/GoogleCloudPlatform/golang-samples/tree/master/appengine

I would be happy to provide further samples under this location (GAE Standard specific)

In this case: https://github.com/GoogleCloudPlatform/golang-samples/tree/master/appengine/logging

However, I noted that the parent README stipulates: "Entirely new samples are not accepted"

Does that apply to these subdirectories? or can I add some samples to that location?

Other samples I have now, and would like to contribute:

- Deploying via gitlab CI
- Sending email with sendgrid
- Connecting to, and querying firestore
- Authenticated requests (firebase issued JWT)

**Comment by tbpg** [comment]
Thanks for the logging links. Hopefully this is cleared up with the second generation runtime. We have some samples using the `appengine/log` package, but I don't think it's worth adding more at this point. Most people consume the samples in this repo by copying + pasting from cloud.google.com.

Yes, it applies to subdirectories. All of the samples in this repo should be embedded in documentation on cloud.google.com. Otherwise, they may not be updated or maintained.

The sample ideas are great. But, they may be better for blog posts or a [community article](https://cloud.google.com/community/), which would both be more discover-able than in this repo.

There is an example for SendGrid here:
* https://github.com/GoogleCloudPlatform/golang-samples/blob/master/docs/appengine/mail/sendgrid/sendgrid.go
* https://cloud.google.com/appengine/docs/standard/go/mail/sendgrid).

Firestore:
* https://github.com/GoogleCloudPlatform/golang-samples/tree/master/firestore/firestore_snippets
* https://firebase.google.com/docs/firestore/quickstart

Tutorial for adding auth to your app with Firestore: https://cloud.google.com/appengine/docs/standard/go/building-app/authenticating-users
