### ISSUE TITLE
docs/appengine/taskqueue: upgrade to Second Gen

### ISSUE THREAD

**Issue by domoritz** [GoogleCloudPlatform/golang-samples#950]
It would be great if you could update https://github.com/GoogleCloudPlatform/golang-samples/blob/master/docs/appengine/taskqueue/app.yaml to use golang 1.11 following https://cloud.google.com/appengine/docs/standard/go111/go-differences.

**Comment by tbpg** [comment]
Thank you for filing this.

https://godoc.org/cloud.google.com/go/cloudtasks/apiv2beta3 is the new library for handling tasks in Second Gen runtimes (App Engine Standard >= Go 1.11), instead of google.golang.org/appengine/taskqueue. Go 1.11 still has access to those APIs, but Go 1.12 does not.

So, this sample is still relevant for people who haven't had the chance to upgrade yet.

You can find the new Cloud Tasks sample here:
* https://cloud.google.com/tasks/docs/creating-appengine-tasks
* https://github.com/GoogleCloudPlatform/golang-samples/tree/master/appengine/go11x/tasks
